# Generated by Django 3.1.7 on 2021-04-04 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201011_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmore',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='students', to='main.Group', verbose_name='Группы'),
        ),
    ]
