# Generated by Django 3.2.2 on 2021-05-07 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210404_1544'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attending',
            old_name='isAttend',
            new_name='is_attend',
        ),
        migrations.RenameField(
            model_name='attending',
            old_name='studySession',
            new_name='study_session',
        ),
        migrations.RenameField(
            model_name='studysession',
            old_name='cancelReason',
            new_name='cancel_reason',
        ),
        migrations.RenameField(
            model_name='studysession',
            old_name='teacherAttended',
            new_name='teacher_attended',
        ),
        migrations.RenameField(
            model_name='timetableelem',
            old_name='beginTime',
            new_name='begin_time',
        ),
        migrations.RenameField(
            model_name='timetableelem',
            old_name='endTime',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='union',
            old_name='occupationReason',
            new_name='occupation_reason',
        ),
    ]
