# Generated by Django 3.2.2 on 2021-05-07 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210507_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attending',
            name='study_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendings', to='main.studysession', verbose_name='Занятие'),
        ),
    ]
